"""
Run AGV simulation with live CoppeliaSim visualization.

Uses the A* classical agent by default (no training required).
Optionally load a trained PPO model with --model.

Prerequisites:
    1. CoppeliaSim is running with the plant scene loaded
       (generated by: python -m src.coppeliasim.scene_builder)
    2. pip install coppeliasim-zmqremoteapi-client

Usage:
    python scripts/run_coppeliasim.py
    python scripts/run_coppeliasim.py --n_agvs 4 --steps 300 --delay 0.1
    python scripts/run_coppeliasim.py --model models/ppo_agent.zip
"""

import argparse
import sys

from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from src.agents.astar_agent import AStarAgent
from src.coppeliasim.bridge import CoppeliaSimBridge
from src.env.agv_fleet_env import AGVFleetEnv


def parse_args() -> argparse.Namespace:
    p = argparse.ArgumentParser(description="AGV simulation with CoppeliaSim visualization")
    p.add_argument("--n_agvs",    type=int,   default=4,    help="Number of AGVs (default 4)")
    p.add_argument("--n_tasks",   type=int,   default=8,    help="Max simultaneous tasks (default 8)")
    p.add_argument("--steps",     type=int,   default=500,  help="Steps per episode (default 500)")
    p.add_argument("--delay",        type=float, default=0.08, help="Seconds per env step (default 0.08)")
    p.add_argument("--interp_steps", type=int,   default=8,    help="Sub-frames for smooth movement (1=discrete, default 8)")
    p.add_argument("--episodes",     type=int,   default=1,    help="Number of episodes to run (default 1)")
    p.add_argument("--model",     type=str,   default=None, help="Path to a trained PPO .zip model (optional)")
    p.add_argument("--host",      type=str,   default="localhost")
    p.add_argument("--port",      type=int,   default=23000)
    return p.parse_args()


def load_agent(args, env: AGVFleetEnv):
    if args.model:
        try:
            from stable_baselines3 import PPO
            from src.agents.ppo_agent import PPOAgent
            model = PPO.load(args.model, env=env)
            agent = PPOAgent(model=model)
            print(f"[run] Loaded PPO model from {args.model}")
            return agent
        except Exception as exc:
            print(f"[run] WARNING: Could not load PPO model ({exc}). Falling back to A*.")

    print("[run] Using A* greedy agent.")
    return AStarAgent()


def run_episode(env: AGVFleetEnv, agent, bridge: CoppeliaSimBridge, args) -> dict:
    _, _ = env.reset()
    bridge.sync(env.agvs)   # push initial positions
    agent.reset()

    for step in range(args.steps):
        action = agent.select_action(env)
        _, _, terminated, truncated, info = env.step(action)
        bridge.sync_tasks(env.tasks)
        bridge.sync(
            env.agvs,
            interp_steps=args.interp_steps,
            step_delay=args.delay / max(args.interp_steps, 1),
        )

        if (step + 1) % 50 == 0:
            print(
                f"  step {step + 1:>4}/{args.steps}"
                f"  tasks_done={info['tasks_completed']}"
                f"  collisions={info['collisions']}"
                f"  utilization={info['mean_utilization']:.2f}"
            )

        if terminated or truncated:
            break

    return info


def main() -> None:
    args = parse_args()

    env = AGVFleetEnv(
        n_agvs=args.n_agvs,
        n_tasks_max=args.n_tasks,
        max_steps=args.steps,
    )
    agent = load_agent(args, env)
    bridge = CoppeliaSimBridge(n_agvs=args.n_agvs, host=args.host, port=args.port)
    # Do NOT start simulation — KUKA Omnirob has internal Lua scripts that
    # fight kinematic setObjectPosition when physics is running.

    try:
        for ep in range(args.episodes):
            print(f"\n[run] Episode {ep + 1}/{args.episodes}")
            info = run_episode(env, agent, bridge, args)
            print(
                f"[run] Episode done — "
                f"tasks={info['tasks_completed']}  "
                f"collisions={info['collisions']}  "
                f"avg_cycle={info['avg_cycle_time']:.1f}  "
                f"utilization={info['mean_utilization']:.2f}"
            )
    except KeyboardInterrupt:
        print("\n[run] Interrupted by user.")
    finally:
        bridge.close()
        env.close()


if __name__ == "__main__":
    main()
